const CHECKS=[["horiz12","Horiz run: opening every 12 ft or 20x20"],["turns","Opening at every direction change"],["damper18","Damper panel within 18 in"],["fan3","Fan access within 3 ft"],["upblast","Upblast housing 3x5 or 4in round"],["vertFloor","Vertical shaft opening each floor"],["gasket","Same metal, 1500F gasket, grease-tight"],["sign","ACCESS PANEL — DO NOT OBSTRUCT"],["drawing","§4.6 drawing on premises"]];
const KEY="nexus.truth.archive.v2"; const TECH="nexus.truth.tech";
const $=id=>document.getElementById(id);
CHECKS.forEach(([id,t])=>{$("checks").insertAdjacentHTML("beforeend",`<label class="check"><input type="checkbox" id="c_${id}"/>${t}</label>`);});
document.querySelectorAll(".nav button").forEach(b=>{b.onclick=()=>{document.querySelectorAll(".nav button").forEach(x=>x.classList.remove("on"));document.querySelectorAll(".pane").forEach(x=>x.classList.remove("on"));b.classList.add("on");$(b.dataset.p).classList.add("on");};});
function toast(m){const t=$("toast");t.textContent=m;t.style.display="block";setTimeout(()=>t.style.display="none",1600);}
$("tech").value=localStorage.getItem(TECH)||""; $("tech").onchange=()=>localStorage.setItem(TECH,$("tech").value);
let gps=null;
$("btnGps").onclick=()=>{if(!navigator.geolocation){toast("No geolocation");return;}navigator.geolocation.getCurrentPosition(p=>{gps={lat:+p.coords.latitude.toFixed(6),lon:+p.coords.longitude.toFixed(6),acc:Math.round(p.coords.accuracy)};$("gpsChip").textContent="GPS "+gps.lat.toFixed(4);toast("GPS pinned");},()=>toast("GPS denied"),{enableHighAccuracy:true,timeout:12000});};
const canvas=$("sk"),ctx=canvas.getContext("2d"); let strokes=[],cur=null,panelMode=false;
function pos(e){const r=canvas.getBoundingClientRect();const s=e.touches?e.touches[0]:e;return[(s.clientX-r.left)*canvas.width/r.width,(s.clientY-r.top)*canvas.height/r.height];}
function draw(){ctx.fillStyle="#07070b";ctx.fillRect(0,0,canvas.width,canvas.height);ctx.lineCap="round";strokes.forEach(s=>{if(s.kind==="panel"){ctx.fillStyle="#ff0080";ctx.beginPath();ctx.arc(s.pts[0][0],s.pts[0][1],10,0,Math.PI*2);ctx.fill();}else{ctx.strokeStyle="#00ff87";ctx.lineWidth=4;ctx.beginPath();s.pts.forEach((p,i)=>i?ctx.lineTo(p[0],p[1]):ctx.moveTo(p[0],p[1]));ctx.stroke();}});}
canvas.addEventListener("pointerdown",e=>{canvas.setPointerCapture(e.pointerId);cur={kind:panelMode?"panel":"line",pts:[pos(e)]};strokes.push(cur);panelMode=false;draw();});
canvas.addEventListener("pointermove",e=>{if(!cur||cur.kind==="panel")return;cur.pts.push(pos(e));draw();});
canvas.addEventListener("pointerup",()=>{cur=null;});
$("undo").onclick=()=>{strokes.pop();draw();};$("clearSk").onclick=()=>{strokes=[];draw();};$("markPanel").onclick=()=>{panelMode=true;toast("Tap sketch for panel");};draw();
function u16(v,o,le){return v.getUint16(o,le)} function u32(v,o,le){return v.getUint32(o,le)}
function readStr(buf,off,n){return new TextDecoder("latin1").decode(buf.slice(off,off+n)).replace(/\0+$/,"")}
function rat(v,o,le){const n=v.getUint32(o,le),d=v.getUint32(o+4,le);return d?n/d:0}
function parseExif(buf){const u8=new Uint8Array(buf);if(u8[0]!==0xFF||u8[1]!==0xD8)return{ok:false};let i=0;while(i<u8.length-4){if(u8[i]!==0xFF){i++;continue;}const m=u8[i+1];if(m===0xDA)break;const len=(u8[i+2]<<8)|u8[i+3];if(m===0xE1&&readStr(buf,i+4,4)==="Exif")return parseTiff(buf,i+10);i+=2+len;}return{ok:false};}
function parseTiff(buf,off){const v=new DataView(buf),le=readStr(buf,off,2)==="II";if(u16(v,off+2,le)!==42)return{ok:false};const tags=readIFD(v,buf,off,off+u32(v,off+4,le),le);const out={ok:true,make:tags[0x010F],model:tags[0x0110],dt:tags[0x0132]};if(tags[0x8769]){const ex=readIFD(v,buf,off,off+tags[0x8769],le);out.dto=ex[0x9003]||out.dt;}if(tags[0x8825]){const g=readIFD(v,buf,off,off+tags[0x8825],le);out.lat=gpsDms(g[0x0002],g[0x0001]);out.lon=gpsDms(g[0x0004],g[0x0003]);}return out;}
function readIFD(v,buf,tiff,ifd,le){const n=u16(v,ifd,le),tags={};for(let i=0;i<n;i++){const e=ifd+2+i*12,tag=u16(v,e,le),typ=u16(v,e+2,le),cnt=u32(v,e+4,le);let valoff=e+8;const size=({1:1,2:1,3:2,4:4,5:8}[typ]||1)*cnt;if(size>4)valoff=tiff+u32(v,e+8,le);if(typ===2)tags[tag]=readStr(buf,valoff,cnt);else if(typ===3)tags[tag]=u16(v,valoff,le);else if(typ===4)tags[tag]=u32(v,valoff,le);else if(typ===5&&cnt>=3)tags[tag]=[rat(v,valoff,le),rat(v,valoff+8,le),rat(v,valoff+16,le)];else if(typ===5)tags[tag]=rat(v,valoff,le);}return tags;}
function gpsDms(dms,ref){if(!dms||!Array.isArray(dms))return null;let d=dms[0]+dms[1]/60+dms[2]/3600;if(ref==="S"||ref==="W")d=-d;return Math.round(d*1e6)/1e6;}
function sample(img){const c=document.createElement("canvas");c.width=48;c.height=48;const x=c.getContext("2d");x.drawImage(img,0,0,48,48);const d=x.getImageData(0,0,48,48).data;let sky=0,metal=0,dark=0,n=48*48;for(let i=0;i<d.length;i+=4){const lum=(d[i]+d[i+1]+d[i+2])/3;if(d[i+2]>d[i]+20&&lum>90)sky++;if(Math.abs(d[i]-d[i+1])<12&&Math.abs(d[i]-d[i+2])<12&&lum>90&&lum<210)metal++;if(lum<40)dark++;}return{sky:sky/n,metal:metal/n,dark:dark/n};}
async function compress(img){const c=document.createElement("canvas");const w=Math.min(900,img.naturalWidth||900);const h=Math.round((img.naturalHeight||600)*w/(img.naturalWidth||900));c.width=w;c.height=h;c.getContext("2d").drawImage(img,0,0,w,h);return c.toDataURL("image/jpeg",0.62);}
let photos=[];
async function tagFiles(files){photos=[];for(const file of files){const buf=await file.arrayBuffer();const exif=parseExif(buf);const url=URL.createObjectURL(file);const img=new Image();img.src=url;await img.decode().catch(()=>{});const vis=img.naturalWidth?sample(img):null;const thumb=img.naturalWidth?await compress(img):null;const name=(file.name||"").toLowerCase();let component="unknown",conf=0.25,tags=[];if(exif.ok&&(exif.dto||exif.dt)){tags.push(["c","taken"]);conf+=0.15;}else tags.push(["y","no time"]);if(exif.lat!=null){tags.push(["c","gps"]);conf+=0.2;}else tags.push(["y","no photo GPS"]);if(/hood|canopy/.test(name)){component="hood";conf+=0.2;}if(/fan|upblast|roof/.test(name)){component="fan";conf+=0.2;}if(/panel|access/.test(name)){component="panel";conf+=0.2;}if(vis&&vis.sky>0.18&&vis.metal>0.12){component=component==="unknown"?"fan":component;tags.push(["g","roof+metal"]);conf+=0.1;}else if(vis&&vis.metal>0.22){component=component==="unknown"?"hood":component;tags.push(["g","stainless"]);}if(vis&&vis.dark>0.45)tags.push(["y","dark — reshoot"]);const grade=conf>=0.7?"VERIFIED_AUTO":conf>=0.45?"REVIEW":"CLAIMED";tags.unshift([grade==="VERIFIED_AUTO"?"g":grade==="REVIEW"?"y":"p",grade]);photos.push({name:file.name,component,conf,grade,tags,exif,thumb});}const withG=photos.filter(p=>p.exif.lat!=null);if(withG.length>=2){const lat=withG.reduce((s,p)=>s+p.exif.lat,0)/withG.length;const lon=withG.reduce((s,p)=>s+p.exif.lon,0)/withG.length;withG.forEach(p=>{const d=Math.hypot(p.exif.lat-lat,p.exif.lon-lon)*111000;p.tags.push(d<80?["g","same-roof"]:["y",Math.round(d)+"m off"]);});}renderPhotos();}
function renderPhotos(){$("photoOut").innerHTML=photos.map(p=>`<div class="item">${p.thumb?`<img class="thumb" src="${p.thumb}" alt=""/>`:""}<div style="font-size:12px;margin-top:6px">${p.name} · ${p.component}</div><div>${p.tags.map(t=>`<span class="tag ${t[0]}">${t[1]}</span>`).join("")}</div></div>`).join("")||'<div class="warn">No shots tagged.</div>';}
$("tagRoll").onclick=()=>{const files=[...$("files").files];if(!files.length){toast("Pick photos");return;}tagFiles(files);};
$("clearPhotos").onclick=()=>{photos=[];$("files").value="";renderPhotos();};
function loadLib(){try{return JSON.parse(localStorage.getItem(KEY)||"[]")}catch{return[]}}
function saveLib(a){localStorage.setItem(KEY,JSON.stringify(a));renderLib();}
function packet(){const checks={};CHECKS.forEach(([id])=>checks[id]=!!$("c_"+id).checked);return{id:crypto.randomUUID(),savedAt:new Date().toISOString(),name:$("name").value.trim(),addr:$("addr").value.trim(),ahj:$("ahj").value.trim(),access:$("access").value,gm:$("gm").value.trim(),hoods:+$("hoods").value||0,fans:+$("fans").value||0,ductft:+$("ductft").value||0,path:$("path").value.trim(),sketch:strokes,checks,deficiencies:$("def").value.trim(),stamp:$("stamp").value,tech:$("tech").value.trim(),gps,photos:photos.map(p=>({name:p.name,component:p.component,grade:p.grade,conf:p.conf,exif:p.exif,thumb:p.thumb})),layer:"VERIFIED"};}
function renderLib(){const a=loadLib();$("libCount").textContent=a.length+" SITES";$("archive").innerHTML=a.slice().reverse().map(s=>`<div class="item"><div><b>${s.name||"(unnamed)"}</b></div><div style="font-size:11px;color:#89b9c0">${s.addr||""} · ${s.stamp} · ${(s.savedAt||"").slice(0,16)}</div><div class="${s.deficiencies?"bad":"ok"}" style="font-size:12px">${s.deficiencies?s.deficiencies.slice(0,140):"No deficiencies noted"}</div></div>`).join("")||'<div style="color:#667">Empty. First save starts the library.</div>';}
renderLib();
$("save").onclick=()=>{const p=packet();if(!p.name&&!p.addr){toast("Name or address first");return;}const a=loadLib();a.push(p);saveLib(a);toast("Packet saved");};
$("export").onclick=()=>{const blob=new Blob([JSON.stringify(loadLib(),null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="nexus-truth-archive.json";a.click();};
$("print").onclick=()=>{const p=packet();const w=window.open("","_blank");w.document.write(`<pre style="font:13px/1.4 ui-monospace,monospace;white-space:pre-wrap">${JSON.stringify({...p,photos:p.photos.map(x=>({...x,thumb:x.thumb?"[jpeg]":null}))},null,2)}</pre>`);w.document.close();w.print();};
$("wipe").onclick=()=>{if(confirm("Wipe local archive?")){saveLib([]);toast("Wiped");}};
if("serviceWorker" in navigator)navigator.serviceWorker.register("./sw.js").catch(()=>{});
